##Dont Change This, It Will Reset The Config If You Do!
ConfigVersion: 2
## If Set To True Any Player With Homespawn.admin Will Receive A Notification If There Is An Update
UpdateNotification: true
## If Set To True The Plugin Will Send Usage Information To mcstats.org, Such As Minecraft Version And Players Online
Metrics: true
## This Limit Only Affects Players With The VIP Perm, Admins Will Be Able To Exceed This Limit (Includes The /Home One)
VIPHomesLimit: 3
## This Limit Affects Players With The homespawn.admin Perm
AdminHomesLimit: 5
## This Time Is How Long THe Player Must Wait Without Being Hit By Another Player Before They Teleport, Set To 0 To Disable
TeleportTime: 10
## If enabled the player wil be given a book with all player commands listed (Does not contain admin or VIP commands) on first join
CommandBook: true
## When enabled players with more than 1 home will be given an inventory menu to select a home to teleport to when they run /homeslist
InventoryMenu: true