name: HomeSpawn
main: net.lapismc.HomeSpawn.HomeSpawn
version: Beta 0.1.7
description: >
             The Basic Home And Spawn Plugin
commands:
  home:
    description: Sends the player to the home they set with /sethome
  sethome:
    description: Sets your home so you can use /home to get back there
  delhome:
    description: Removes your home, this means you cant use /home untill you reset your home with /sethome
  spawn:
    description: Sends you to the place that spawn was set
  setspawn:
    description: Sets the spawn location for the server so you can use /spawn to get back there
  delspawn:
    description: Deleates the spawn location from file
  homespawn:
    description: Shows Plugin Infomation
  homeslist:
    description: Shows The Current Homes
  homepassword:
    description: Allows the player to set a password and transfer homes to a new username on an offline mode server